FROM php:8.2-fpm

# Pacotes do sistema
RUN apt-get update && apt-get install -y \
    git curl zip unzip libpq-dev libicu-dev libzip-dev libpng-dev \
    libjpeg62-turbo-dev libfreetype6-dev libssl-dev libxml2-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    # Extensões PHP necessárias (inclui pcntl/posix p/ Horizon)
    && docker-php-ext-install pdo pdo_mysql intl mbstring zip gd bcmath pcntl posix \
    && rm -rf /var/lib/apt/lists/*

# Redis (fila/cache)
RUN pecl install redis && docker-php-ext-enable redis

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# Otimizações/ambiente
ENV COMPOSER_ALLOW_SUPERUSER=1 \
    PHP_OPCACHE_VALIDATE_TIMESTAMPS=1

# Permissões
RUN chown -R www-data:www-data /var/www/html

CMD ["php-fpm"]
